apiVersion: v1
kind: ConfigMap
metadata:
  name: daef-prometheus-scrape
  namespace: monitoring
data:
  prometheus-additional.yaml: |
    scrape_configs:
      - job_name: daef-gateway
        metrics_path: /v1/metrics/prometheus
        scrape_interval: 15s
        static_configs:
          - targets:
              - daef-api-gateway.default.svc.cluster.local:8080
            labels:
              app: daef-gateway
