version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: daef-postgres
    environment:
      POSTGRES_USER: daef
      POSTGRES_PASSWORD: daef
      POSTGRES_DB: daef
    ports:
      - "5432:5432"
    volumes:
      - daef_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: daef-redis
    ports:
      - "6379:6379"

volumes:
  daef_pgdata:
