apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: splai-system
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - api-gateway.yaml
  - planner.yaml
  - scheduler.yaml
  - operator.yaml
