apiVersion: apps/v1
kind: Deployment
metadata:
  name: splai-operator
  namespace: splai-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splai-operator
  template:
    metadata:
      labels:
        app: splai-operator
    spec:
      serviceAccountName: splai-operator
      containers:
        - name: operator
          image: ghcr.io/example/splai-operator:v0.1.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: splai-operator
  namespace: splai-system
