{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "splai.fullname" . }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "splai.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "splai.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
{{- if eq (default "openshift" .Values.postgres.flavor) "openshift" }}
            - name: POSTGRESQL_USER
              value: {{ .Values.postgres.auth.username | quote }}
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.postgres.auth.password | quote }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgres.auth.database | quote }}
{{- else }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.auth.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database | quote }}
{{- end }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: {{ .Values.postgres.dataMountPath | quote }}
      volumes:
        - name: postgres-data
{{- if .Values.postgres.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "splai.fullname" . }}-postgres
{{- else }}
          emptyDir: {}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splai.fullname" . }}-postgres
spec:
  selector:
    app: {{ include "splai.fullname" . }}-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
{{- if .Values.postgres.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "splai.fullname" . }}-postgres
spec:
  accessModes:
{{ toYaml .Values.postgres.persistence.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
{{- if .Values.postgres.persistence.storageClassName }}
  storageClassName: {{ .Values.postgres.persistence.storageClassName | quote }}
{{- end }}
{{- end }}
{{- end }}
