{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "splai.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "splai.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "splai.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splai.fullname" . }}-redis
spec:
  selector:
    app: {{ include "splai.fullname" . }}-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
{{- end }}
