apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: daefpolicies.daef.io
spec:
  group: daef.io
  scope: Namespaced
  names:
    plural: daefpolicies
    singular: daefpolicy
    kind: DAEFPolicy
    shortNames:
      - dp
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deny:
                  type: array
                  items:
                    type: object
                    properties:
                      model:
                        type: string
                      when:
                        type: string
                allowModels:
                  type: array
                  items:
                    type: string
                maxConcurrentTasks:
                  type: integer
      additionalPrinterColumns:
        - name: MaxTasks
          type: integer
          jsonPath: .spec.maxConcurrentTasks
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
